### ISSUE TITLE
Chart sizing wrong in Nextjournal

### ISSUE THREAD

**Issue by jheer** [uwdata/visualization-curriculum#17]
For example, see: https://github.nextjournal.com/uwdata/visualization-curriculum/blob/master/altair_interaction.ipynb

Some of the chart views in the notebook are not properly sized (widgets are below the fold, or even whole charts are not properly captured). This may be a Nextjournal issue; don't know if there is something we can do on our end to fix this.

@domoritz any ideas? I haven't used Nextjournal before and I _think_ you merged these additions?

**Comment by domoritz** [comment]
@mk can you look at this?

**Comment by zampino** [comment]
@jheer @domoritz 👋 we'll be very glad to help. What I'm seeing at the linked URL is, for instance, a y-overflow of the result charts which is hidden on the right: 

<img width="600" alt="CleanShot 2021-03-24 at 15 29 17@2x" src="https://user-images.githubusercontent.com/1078464/112327625-de364580-8cb5-11eb-801a-96eee41eb80d.png">

or
 
<img width="600" alt="CleanShot 2021-03-24 at 15 31 08@2x" src="https://user-images.githubusercontent.com/1078464/112327788-03c34f00-8cb6-11eb-94ab-91318309468a.png">

@jheer Is this what you mean by 

> widgets are below the fold

with _widget_ for the (...) altair controls button?

This doesn't happen on colab indeed (which uses whole window layout).

**Comment by domoritz** [comment]
Thank you @zampino for looking into the issues.

Some of the overflow is not great but there are a few bigger issues. For example, some charts are almost completely gone.

<img width="783" alt="Screen Shot 2021-03-24 at 07 39 01" src="https://user-images.githubusercontent.com/589034/112328964-0309c900-8c74-11eb-8fa4-a999bc863e86.png">

What @jheer referred to with "widgets are below the fold" are the inputs that you need to scroll to. This issue is problematic as readers will likely miss that they can interact with charts at all. 

<img width="825" alt="Screen Shot 2021-03-24 at 07 39 34" src="https://user-images.githubusercontent.com/589034/112329149-2f254a00-8c74-11eb-9725-d9216717bb32.png">
<img width="816" alt="Screen Shot 2021-03-24 at 07 39 37" src="https://user-images.githubusercontent.com/589034/112329166-33e9fe00-8c74-11eb-819f-96d3be621a90.png">

**Comment by zampino** [comment]
@domoritz thank you for the detailed report! I think the common pattern there is failing to calculate the charts heights, which might even result into showing just a tiny slice of the plot. We'll investigate the issue.

**Comment by domoritz** [comment]
Yeah, it looks like concatenated plots have almost no height and for single view plots the height isn just the height of the chart. Can you instead use the height of the HTML element?

**Comment by mk** [comment]
Hi @jheer and @domoritz, we've just deployed a fix for the sizing bug on our side so this issue can be closed. Thanks a lot for letting us know!

**Comment by jheer** [comment]
Fantastic, thank you!
